config/routes.rb
Tcproj::Application.routes.draw do
  
  
  get "subscriptions/create"

  get "subscriptions/destroy"

  get "qresponses/new"

  get "qresponses/show"

  get "qresponses/index"

  get "questionnaires/new"

  get "questionnaires/create"

  get "questionnaires/show"

  get "cbo_community_memberships/create"

  get "cbo_community_memberships/destroy"

  get "communities/new"

  get "communities/show"

  get "communities/index"

  get "user_community_memberships/create"

  get "user_community_memberships/destroy"

  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/nearby_cbos', :to => 'cboprofiles#nearby'
  match '/my_cbos', :to => 'cbos#my'
  match '/map', :to => 'pages#map'
  get "sessions/new"

  get "categorizations/new"
    
  
  root :to => "pages#home"
  
  resources :users do
    collection do
      get 'confirmpage'
      post 'confirm'
    end
  end
  
  resources :cbos do
    collection do
      get 'confirmpage'
      get 'my'
      post 'confirm'
    end
  end
  
  resources :cboprofiles do
    collection do
      get 'nearby'
    end
  end
  
  resources :communities do
    collection do
      get 'nearby'
      get 'my'
    end
  end
  
  resources :questionnaires do
    member do
      get 'reply'
    end
  end
  
  resources :pages do
    member do
      get 'map'
    end
  end
  
  resources :memberships do
    member do
      put 'confirm'
    end
  end
  
  resources :participations do
    member do
      put 'change_status'
    end
    
    collection do
      get 'my'
    end
  end
  
  resources :qresponses do
    collection do
      get 'my'
    end
  end
  
  resources :participation_messages do
    
  end
  
  
  resources :userprofiles
  resources :cboprofiles
  resources :cbos
  resources :categories
  resources :participations
  resources :communities
  resources :user_community_memberships
  resources :cbo_community_memberships
  
  resources :pages
  resources :subscriptions

    

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"
  

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  
  
  
  # attr_accessible :status
  serialize :monday
  serialize :tuesday
  serialize :wednesday
  serialize :thursday
  serialize :friday
  serialize :saturday
  serialize :sunday
  
  attr_accessible :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday
  attr_accessible :cbo_id
  
  attr_accessible :status, :partysize
  
  has_many :participation_messages
  
 
 
  belongs_to :user, :class_name => "User"
  belongs_to :cbo, :class_name => "Cbo"
  
  validates :user_id, :presence => true
  validates :cbo_id, :presence => true
  
  validates :partysize, :presence => true, :numericality => { :greater_than => 0}
  
  validates_uniqueness_of :cbo_id, :scope => :user_id
  
  
  # custom validation for user/cbo uniqueness
  #validate :validate_user_cbo_uniqueness
  
  
  #after_initialize :set_default_schedule
  
  def set_status(status_level)
    # status level 0 - unconfirmed
    # status level 1 - more info
    # status level 2 - confirmed
    
    
    if status_level.to_i <= 2 && status_level.to_i >= 0
      self.status = status_level.to_i
    end
    
  end
  
  def status_string
    
    case self.status
		when 0
			status_string = "not confirmed"
		when 1
			status_string = "need more info"
		when 2
			status_string = "accepted"
		end
    
    
  end 
  
=begin  
  def validate_user_cbo_uniqueness
    
    if user = User.find(user_id)
      errors.add(:cbo_id, "already has a participation with #{user.userprofile}") if user.participations.find_by_cbo_id(cbo_id)
    end
  end
=end  
  def set_default_schedule
    
    day_schedule = {
      :hour0 => 0,
      :hour1 => 0,
      :hour2 => 0,
      :hour3 => 0,
      :hour4 => 0,
      :hour5 => 0,
      :hour6 => 0,
      :hour7 => 0,
      :hour8 => 0,
      :hour9 => 0,
      :hour10 => 0,
      :hour11 => 0,
      :hour12 => 0,
      :hour13 => 0,
      :hour14 => 0,
      :hour15 => 0,
      :hour16 => 0,
      :hour17 => 0,
      :hour18 => 0,
      :hour19 => 0,
      :hour20 => 0,
      :hour21 => 0,
      :hour22 => 0,
      :hour23 => 0
      
    }
    
    #self.cbo_id = 9000
    self.monday = day_schedule
    self.tuesday = day_schedule
    self.wednesday = day_schedule
    self.thursday = day_schedule
    self.friday = day_schedule
    self.saturday = day_schedule
    self.sunday = day_schedule
  end
  
  
end



# == Schema Information
#
# Table name: participations
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  cbo_id     :integer
#  status     :integer         default(0)
#  monday     :text
#  tuesday    :text
#  wednesday  :text
#  thursday   :text
#  friday     :text
#  saturday   :text
#  sunday     :text
#  created_at :datetime
#  updated_at :datetime
#  partysize  :integer         default(1)
#

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  
  before_filter :authenticate_user, :only => [:new, :create, :edit, :my]
  
  def new
    @participation = Participation.new
    @participation.set_default_schedule # there's probably a better way to do this...
  end
  
  def my
    @participations = current_user.participations
  end
  
  def create
    @participation = current_user.participations.new()
    @participation.set_default_schedule # there's probably a better way to do this...
    
    @participation.attributes = params[:participation]
    if @participation.save

      # update view participation messages
      @participation.user.post_participation_message(@participation, "#{current_user.userprofile.name} created participation.")
      redirect_to @participation.cbo.cboprofile, :flash => {:success => "Successfully sent your application! Please wait further instructions."}
    
      # send an email out
      ParticipationMessageMailer.deliver_new_participation(@participation)
    else
      render 'new'
    end
  end
  
  def index
    @participations = Participation.all
  end
  
  def show
    @participation = Participation.find(params[:id])
    #@new_participation_message = ParticipationMessage.new
  end
  
  def edit
    @participation = Participation.find(params[:id])
  end
  
  def update
    @participation = Participation.find(params[:id])
    #params[:participation][:status].to_i
    if @participation.update_attributes(params[:participation])
      
      if signed_in_cbo?
        # log via a ParticipationMessage                   
        @participation.cbo.post_participation_message(@participation, "#{current_cbo.cboprofile.name} updated status to #{@participation.status_string.titlecase}.")
        redirect_to @participation.cbo, :flash => {:success => "Successfully changed confirmation level."}
        
        # Send mail using mailer
        ParticipationMessageMailer.deliver_status_changed(@participation)
        
      else
        # user
        # log via a ParticipationMessage
        @participation.user.post_participation_message(@participation, "#{current_user.userprofile.name} updated schedule.")
        redirect_to @participation.cbo.cboprofile, :flash => {:success => "Successfully updated your participation"}
        
        # Send mail using mailer
        ParticipationMessageMailer.deliver_schedule_changed(@participation)
    
      end
    else
      render 'edit'
    end
  end
  
  def change_status
    @participation = Participation.find(params[:id])
  end
  
  
  
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_day_hour_fields.html.erb
<%= participation_form.fields_for day_of_week, do |day_form| %>

	<%= day_of_week %>:<br />
	
	<% (0..23).each do |hour_num| %>
	
		<% hour_key = "hour#{hour_num}" %>
	
		<%= day_form.hidden_field hour_key.to_sym, :value => 0 %>
		<%= check_box_tag "participation[#{day_of_week.to_s}][#{hour_key}]", 
			"1",
		 	@participation[day_of_week][hour_key] == "1" ? true : false 
		%>
	<% end %>

<% end %>

app/views/participations/_fields.html.erb
	
<div class="clearfix">
	<%= participation_form.label :cbo_id, :class => "xlInput" %>
	<div class="input">
		<%= participation_form.select(:cbo_id, Cbo.all.collect {|cbo| [cbo.cboprofile.name, cbo.id] }, :prompt => true) %>
	</div>
</div>


<% ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].each do |day_of_week| %>

	<%= render 'day_hour_fields', :day_of_week => day_of_week, :participation_form => participation_form %>
	<hr />	
	
<% end %>

app/views/participations/_modal_reply.html.erb
<%= render 'participations/participation_stylesheet' %>	
	
<%= render 'participations/participation_display_js' %>

<script language="javascript">
	function changeCellColor(td)
	{
	    var node = td;
	    while ( (node = node.parentNode) != null )
	    {
	        if ( node.tagName == "TD" )
	        {
	            //node.style.backgroundColor = td.checked ? "lightgreen" : "transparent";
				node.className = td.checked ? "selectedCell" : "unselectedCell";
	            return;
	        }
	    }
	    // not found...give up?
	}
</script>


<h1>Participation Schedule</h1>
<%
	if participation[:cbo_id]
		cbo = Cbo.find_by_id(participation[:cbo_id])
		cbo_name = cbo.cboprofile.name
	else
		cbo_name = "this organization."
		
	end

%>


<p>Please select which times you would be available to volunteer for <%= cbo_name %>.</p><br />

<%= form_for participation, :html => { :multipart => true } do |participation_form| %>
	<%= render 'shared/error_messages', :object => participation_form.object %>
	
	<%= participation_form.hidden_field :cbo_id, :value => participation[:cbo_id] %>
		
<table class="bordered-table condensed-table" id="scheduleTable">
	<thead>
		<th>Hour</th>
		<th>Monday</th>
		<th>Tuesday</th>
		<th>Wednesday</th>
		<th>Thursday</th>
		<th>Friday</th>
		<th>Saturday</th>
		<th>Sunday</th>
	</thead>
	<tbody>
		
		<% (0..23).each do |hour_num| # for each hour %>
			
			
			
			<% if hour_num == 0 # show the toggle times %>
				<tr>
					<td onMouseDown="showHideMorning()" colspan="8">Show/Hide Morning Times</td>
				</tr>
				
			<% end %>
			
			
			
			
			<% if (hour_num >= 0 && hour_num <= 8) # hide the morning section %>
				<tr style="display: none;" class="morningRow" id="row_<%= hour_num %>">
					
			<% elsif (hour_num >= 18 && hour_num <= 23) # hide the evening section %>
				<tr style="display: none;" class="eveningRow" id="row_<%= hour_num %>">
					
			<% else # draw as normal %>
				<tr id="row_<%= hour_num %>">
					
			<% end %>

				
					<% hour_key = "hour#{hour_num}" # string-ify it %>
					<td><%= (hour_num % 12 == 0 ? "12" : (hour_num % 12).to_s) + (hour_num < 12 ? " AM" : " PM") %></td>
					
					<% ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].each do |day_of_week| %>
				
						<%= participation_form.fields_for day_of_week do |day_form| %>
					
							<td class="<%= participation[day_of_week][hour_key] == "1" ? "selectedCell" : "unselectedCell" %>">
								<%= day_form.hidden_field hour_key.to_sym, :value => 0 %>
								<%= check_box_tag "participation[#{day_of_week.to_s}][#{hour_key}]", 
									"1",
								 	participation[day_of_week][hour_key] == "1" ? true : false,
								 	:onClick => "changeCellColor(this);"
								%>
							</td>
				
						<% end %>
					<% end %>	
			</tr>
			
			<% if hour_num == 23 # show the toggler for evening times%>
				<tr>
					<td onMouseDown="showHideEvening()" colspan="8">Show/Hide Evening Times</td>
				</tr>
			<% end %>

		<% end %>
	</tbody>
</table>


<p>
How many people are volunteering? <%= participation_form.text_field :partysize, :class => "span2" %>
</p>


<div class="actions">
	<%= participation_form.submit "Create", :class => "btn primary" %>
</div>




<% end %>

app/views/participations/_modal_show.html.erb
<p>You've already submitted a schedule to this CBO. Please wait further instructions, or <%= link_to "edit", edit_participation_path(participation) %> your schedule.</p>
	
	
<p>Your application status is currently: <strong><%= participation.status_string.titlecase %></strong></p>
	
	
<%= render 'participations/participation_stylesheet' %>	
	
<%= render 'participations/participation_display_js' %>


<table class="bordered-table condensed-table" id="scheduleTable">
	<thead>
		<th>Hour</th>
		<th>Monday</th>
		<th>Tuesday</th>
		<th>Wednesday</th>
		<th>Thursday</th>
		<th>Friday</th>
		<th>Saturday</th>
		<th>Sunday</th>
	</thead>
	<tbody>
		
		<% (0..23).each do |hour_num| # for each hour %>
			
			
			
			<% if hour_num == 0 # show the toggle times %>
				<tr>
					<td onMouseDown="showHideMorning()" colspan="8">Show/Hide Morning Times</td>
				</tr>
				
			<% end %>
			
			
			
			
			<% if (hour_num >= 0 && hour_num <= 8) # hide the morning section %>
				<tr style="display: none;" class="morningRow" id="row_<%= hour_num %>">
					
			<% elsif (hour_num >= 18 && hour_num <= 23) # hide the evening section %>
				<tr style="display: none;" class="eveningRow" id="row_<%= hour_num %>">
					
			<% else # draw as normal %>
				<tr id="row_<%= hour_num %>">
					
			<% end %>

				
					<% hour_key = "hour#{hour_num}" # string-ify it %>
					<td><%= (hour_num % 12 == 0 ? "12" : (hour_num % 12).to_s) + (hour_num < 12 ? " AM" : " PM") %></td>
					
					<% ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].each do |day_of_week| %>
				
					
							<td class="<%= participation[day_of_week][hour_key] == "1" ? "selectedCell" : "unselectedCell" %>">
								
								<%= participation[day_of_week][hour_key] == "1" ? "Yes" : "" %>
								
							</td>
				
					<% end %>	
			</tr>
			
			<% if hour_num == 23 # show the toggler for evening times%>
				<tr>
					<td onMouseDown="showHideEvening()" colspan="8">Show/Hide Evening Times</td>
				</tr>
			<% end %>

		<% end %>
	</tbody>
</table>

<p>There <%= participation.partysize == 1 ? 'is' : 'are' %> a total of <%= pluralize(participation.partysize, 'person') %> volunteering.</p>

<%= render 'participation_messages/message_box', :participation => participation %>
<br />

app/views/participations/_participation_display_js.html.erb
<script language="javascript">

function showHideRow(rowId) {
	row = document.getElementById(rowId)
	row.style.display = (row.style.display == 'table-row')? 'none' : 'table-row';
}

function showHideMorning() {
	showHideRow('row_0');
	showHideRow('row_1');
	showHideRow('row_2');
	showHideRow('row_3');
	showHideRow('row_4');
	showHideRow('row_5');
	showHideRow('row_6');
	showHideRow('row_7');
	showHideRow('row_8');
	
}

function showHideEvening() {
	showHideRow('row_18');
	showHideRow('row_19');
	showHideRow('row_20');
	showHideRow('row_21');
	showHideRow('row_22');
	showHideRow('row_23');
	
}

function highlightRow(rowId) {
	row = document.getElementById(rowId)
	row.style.backgroundColor = "#FF0000"
	
}


</script>

app/views/participations/_participation_stylesheet.html.erb
<style type="text/css">

	.selectedCell {
		background-color: #eeffee;
		text-align: center;
	}
	
	.unselectedCell {
		background-color: transparent;
		text-align: center;
	}

	.morningRow {
		background-color: #ffffee;
		
	}
	
	.eveningRow {
		background-color: #eeffff;
	}
	
	#scheduleTable tr:hover {
		background-color: #ffeeee; 
	}
	
	#scheduleTable th {
		text-align: center;
		width: 12.5%;
	}
</style>

app/views/participations/_participation_table_header.html.erb
<table class="bordered-table condensed-table" id="scheduleTable">
	<thead>
		<th style="width: 16%"></th>
		<th style="width: 12%">Monday</th>
		<th style="width: 12%">Tuesday</th>
		<th style="width: 12%">Wednesday</th>
		<th style="width: 12%">Thursday</th>
		<th style="width: 12%">Friday</th>
		<th style="width: 12%">Saturday</th>
		<th style="width: 12%">Sunday</th>
	</thead>
	<tbody>

app/views/participations/create.html.erb
<%= debug @participation %>

app/views/participations/edit.html.erb
<%= render 'participation_stylesheet' %>	
	
<%= render 'participation_display_js' %>

<script language="javascript">
	function changeCellColor(td)
	{
	    var node = td;
	    while ( (node = node.parentNode) != null )
	    {
	        if ( node.tagName == "TD" )
	        {
	            //node.style.backgroundColor = td.checked ? "lightgreen" : "transparent";
				node.className = td.checked ? "selectedCell" : "unselectedCell";
	            return;
	        }
	    }
	    // not found...give up?
	}
</script>

<h1>Participation Schedule</h1>

<p>Please select which times you would be available to volunteer.</p><br />


<%= form_for @participation, :html => { :multipart => true } do |participation_form| %>
	<%= render 'shared/error_messages', :object => participation_form.object %>


<table class="bordered-table condensed-table" id="scheduleTable">
	<thead>
		<th>Hour</th>
		<th>Monday</th>
		<th>Tuesday</th>
		<th>Wednesday</th>
		<th>Thursday</th>
		<th>Friday</th>
		<th>Saturday</th>
		<th>Sunday</th>
	</thead>
	<tbody>
		
		<% (0..23).each do |hour_num| # for each hour %>
			
			
			
			<% if hour_num == 0 # show the toggle times %>
				<tr>
					<td onMouseDown="showHideMorning()" colspan="8">Show/Hide Morning Times</td>
				</tr>
				
			<% end %>
			
			
			
			
			<% if (hour_num >= 0 && hour_num <= 8) # hide the morning section %>
				<tr style="display: none;" class="morningRow" id="row_<%= hour_num %>">
					
			<% elsif (hour_num >= 18 && hour_num <= 23) # hide the evening section %>
				<tr style="display: none;" class="eveningRow" id="row_<%= hour_num %>">
					
			<% else # draw as normal %>
				<tr id="row_<%= hour_num %>">
					
			<% end %>

				
					<% hour_key = "hour#{hour_num}" # string-ify it %>
					<td><%= (hour_num % 12 == 0 ? "12" : (hour_num % 12).to_s) + (hour_num < 12 ? " AM" : " PM") %></td>
					
					<% ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].each do |day_of_week| %>
				
						<%= participation_form.fields_for day_of_week do |day_form| %>
					
							<td class="<%= @participation[day_of_week][hour_key] == "1" ? "selectedCell" : "unselectedCell" %>">
								<%= day_form.hidden_field hour_key.to_sym, :value => 0 %>
								<%= check_box_tag "participation[#{day_of_week.to_s}][#{hour_key}]", 
									"1",
								 	@participation[day_of_week][hour_key] == "1" ? true : false,
								 	:onClick => "changeCellColor(this);"
								%>
							</td>
				
						<% end %>
					<% end %>	
			</tr>
			
			<% if hour_num == 23 # show the toggler for evening times%>
				<tr>
					<td onMouseDown="showHideEvening()" colspan="8">Show/Hide Evening Times</td>
				</tr>
			<% end %>

		<% end %>
	</tbody>
</table>

<p>
How many people are volunteering? <%= participation_form.text_field :partysize, :class => "span2" %>
</p>

<div class="actions">
	<%= participation_form.submit "Edit", :class => "btn primary" %>
</div>


<% end %>

app/views/participations/edit_backup.html.erb
<%= form_for @participation, :html => { :multipart => true } do |participation_form| %>
	<%= render 'shared/error_messages', :object => participation_form.object %>

	<%= render 'fields', :participation_form => participation_form %>





	<div class="actions">
		<%= participation_form.submit "Edit", :class => "btn primary" %>
	</div>

<% end %>

app/views/participations/index.html.erb
<%= link_to "New", new_participation_path %><br />
<% @participations.each do |participation| %>
	<%= link_to "Participation #{participation.id}", participation %> <br/>
<% end %>

app/views/participations/my.html.erb
<% @participations.each do |participation| %>
	<%= link_to "Participation #{participation.id}", participation %> <br/>
<% end %>

app/views/participations/new.html.erb
<%= render 'participation_stylesheet' %>	
	
<%= render 'participation_display_js' %>

<script language="javascript">
	function changeCellColor(td)
	{
	    var node = td;
	    while ( (node = node.parentNode) != null )
	    {
	        if ( node.tagName == "TD" )
	        {
	            //node.style.backgroundColor = td.checked ? "lightgreen" : "transparent";
				node.className = td.checked ? "selectedCell" : "unselectedCell";
	            return;
	        }
	    }
	    // not found...give up?
	}
</script>


<h1>Participation Schedule</h1>

<p>Please select which times you would be available to volunteer.</p><br />

<%= form_for @participation, :html => { :multipart => true } do |participation_form| %>
	<%= render 'shared/error_messages', :object => participation_form.object %>
	
	<%= participation_form.hidden_field :cbo_id, :value => params[:participation][:cbo_id] %>
	
<table class="bordered-table condensed-table" id="scheduleTable">
	<thead>
		<th>Hour</th>
		<th>Monday</th>
		<th>Tuesday</th>
		<th>Wednesday</th>
		<th>Thursday</th>
		<th>Friday</th>
		<th>Saturday</th>
		<th>Sunday</th>
	</thead>
	<tbody>
		
		<% (0..23).each do |hour_num| # for each hour %>
			
			
			
			<% if hour_num == 0 # show the toggle times %>
				<tr>
					<td onMouseDown="showHideMorning()" colspan="8">Show/Hide Morning Times</td>
				</tr>
				
			<% end %>
			
			
			
			
			<% if (hour_num >= 0 && hour_num <= 8) # hide the morning section %>
				<tr style="display: none;" class="morningRow" id="row_<%= hour_num %>">
					
			<% elsif (hour_num >= 18 && hour_num <= 23) # hide the evening section %>
				<tr style="display: none;" class="eveningRow" id="row_<%= hour_num %>">
					
			<% else # draw as normal %>
				<tr id="row_<%= hour_num %>">
					
			<% end %>

				
					<% hour_key = "hour#{hour_num}" # string-ify it %>
					<td><%= (hour_num % 12 == 0 ? "12" : (hour_num % 12).to_s) + (hour_num < 12 ? " AM" : " PM") %></td>
					
					<% ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].each do |day_of_week| %>
				
						<%= participation_form.fields_for day_of_week do |day_form| %>
					
							<td class="<%= @participation[day_of_week][hour_key] == "1" ? "selectedCell" : "unselectedCell" %>">
								<%= day_form.hidden_field hour_key.to_sym, :value => 0 %>
								<%= check_box_tag "participation[#{day_of_week.to_s}][#{hour_key}]", 
									"1",
								 	@participation[day_of_week][hour_key] == "1" ? true : false,
								 	:onClick => "changeCellColor(this);"
								%>
							</td>
				
						<% end %>
					<% end %>	
			</tr>
			
			<% if hour_num == 23 # show the toggler for evening times%>
				<tr>
					<td onMouseDown="showHideEvening()" colspan="8">Show/Hide Evening Times</td>
				</tr>
			<% end %>

		<% end %>
	</tbody>
</table>


<p>
How many people are volunteering? <%= participation_form.text_field :partysize, :class => "span2" %>
</p>

<div class="actions">
	<%= participation_form.submit "Create", :class => "btn primary" %>
</div>


<% end %>

app/views/participations/show.html.erb
<% if signed_in_user? %>
	<h1>Participation Table for <%= link_to @participation.cbo.cboprofile.name, @participation.cbo.cboprofile %></h1>
	
	<%
		status_string = ""
		case @participation[:status]
		when 0
			status_string = "Pending"
		when 1
			status_string = "Need More Information"
		when 2
			status_string = "Accepted"
		end
	%>
	<h2>Current Status: <strong><%= @participation.status_string.titlecase %></strong></h2>
	
	<br />
	
	

	
	<br /> <br />
<% end %>		
	
	
<% if signed_in_cbo? %>
	<h1>Participation Form from <%= @participation.user.userprofile.name %></h1>
	<% if @participation.cbo_id == current_cbo.id %>
	
		<%= form_for @participation do |participation_form| %>
	
			<div class="clearfix">
				<%= participation_form.label :status, :class => "xlInput" %>
				<div class="input">
					<%= participation_form.select :status, 
						options_for_select([['Not Confirmed', 0], ['Need More Info', 1], ['Accepted', 2]], @participation.status)
 					%>

					<%= participation_form.submit "Set Status", :class => "btn primary"%>
				</div>
			</div>
		<% end %>
	
	<% end %>
	
	
	<!-- Information about Student !-->
	<hr />
	<h2>More information on <%= link_to @participation.user.userprofile.name, @participation.user.userprofile %>:</h2>
	
	<h3><%= t(:core_question1_text) %></h3>
	<p><%= @participation.user.userprofile.core_question1_response %></p>
	<br />
	
	<h3><%= t(:core_question2_text) %></h3>
	<p><%= @participation.user.userprofile.core_question2_response %></p>
	<br />
	
	<h3><%= t(:core_question3_text) %></h3>
	<p><%= @participation.user.userprofile.core_question3_response %></p>
	<br />
	
	<h3><%= t(:core_question4_text) %></h3>
	<p><%= @participation.user.userprofile.core_question4_response %></p>
	<br />
	<hr />
	
<% end %>

<% if signed_in_cbo? or signed_in_user? %>

	<p>
	Most recent message (from <%= @participation.participation_messages.last.sender_name %>): <%= @participation.participation_messages.last.message %>
	</p>
<% end %>




	
	
	
	
	
<%= render 'participation_stylesheet' %>	
<%= render 'participation_display_js' %>


<table class="bordered-table condensed-table" id="scheduleTable">
	<thead>
		<th>Hour</th>
		<th>Monday</th>
		<th>Tuesday</th>
		<th>Wednesday</th>
		<th>Thursday</th>
		<th>Friday</th>
		<th>Saturday</th>
		<th>Sunday</th>
	</thead>
	<tbody>
		
		<% (0..23).each do |hour_num| # for each hour %>
			
			
			
			<% if hour_num == 0 # show the toggle times %>
				<tr>
					<td onMouseDown="showHideMorning()" colspan="8">Show/Hide Morning Times</td>
				</tr>
				
			<% end %>
			
			
			
			
			<% if (hour_num >= 0 && hour_num <= 8) # hide the morning section %>
				<tr style="display: none;" class="morningRow" id="row_<%= hour_num %>">
					
			<% elsif (hour_num >= 18 && hour_num <= 23) # hide the evening section %>
				<tr style="display: none;" class="eveningRow" id="row_<%= hour_num %>">
					
			<% else # draw as normal %>
				<tr id="row_<%= hour_num %>">
					
			<% end %>

				
					<% hour_key = "hour#{hour_num}" # string-ify it %>
					<td><%= (hour_num % 12 == 0 ? "12" : (hour_num % 12).to_s) + (hour_num < 12 ? " AM" : " PM") %></td>
					
					<% ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"].each do |day_of_week| %>
				
					
							<td class="<%= @participation[day_of_week][hour_key] == "1" ? "selectedCell" : "unselectedCell" %>">
								
								<%= @participation[day_of_week][hour_key] == "1" ? "Yes" : "" %>
								
							</td>
				
					<% end %>	
			</tr>
			
			<% if hour_num == 23 # show the toggler for evening times%>
				<tr>
					<td onMouseDown="showHideEvening()" colspan="8">Show/Hide Evening Times</td>
				</tr>
			<% end %>

		<% end %>
	</tbody>
</table>

<p>There <%= @participation.partysize == 1 ? 'is' : 'are' %> a total of <%= pluralize(@participation.partysize, 'person') %> volunteering.</p>


<% if signed_in_user? %>
	<% if @participation.user_id == current_user.id %>
		<%= link_to "Edit Schedule", edit_participation_path(@participation) %>
		<br /><br />
	<% end %>
<% end %>

<% if signed_in_user? or signed_in_cbo? %>
	<%= render 'participation_messages/message_box', :participation => @participation %>
	<br />

<% end %>