config/routes.rb
Tcproj::Application.routes.draw do
  
  
  get "subscriptions/create"

  get "subscriptions/destroy"

  get "qresponses/new"

  get "qresponses/show"

  get "qresponses/index"

  get "questionnaires/new"

  get "questionnaires/create"

  get "questionnaires/show"

  get "cbo_community_memberships/create"

  get "cbo_community_memberships/destroy"

  get "communities/new"

  get "communities/show"

  get "communities/index"

  get "user_community_memberships/create"

  get "user_community_memberships/destroy"

  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/nearby_cbos', :to => 'cboprofiles#nearby'
  match '/my_cbos', :to => 'cbos#my'
  match '/map', :to => 'pages#map'
  get "sessions/new"

  get "categorizations/new"
    
  
  root :to => "pages#home"
  
  resources :users do
    collection do
      get 'confirmpage'
      post 'confirm'
    end
  end
  
  resources :cbos do
    collection do
      get 'confirmpage'
      get 'my'
      post 'confirm'
    end
  end
  
  resources :cboprofiles do
    collection do
      get 'nearby'
    end
  end
  
  resources :communities do
    collection do
      get 'nearby'
      get 'my'
    end
  end
  
  resources :questionnaires do
    member do
      get 'reply'
    end
  end
  
  resources :pages do
    member do
      get 'map'
    end
  end
  
  resources :memberships do
    member do
      put 'confirm'
    end
  end
  
  resources :participations do
    member do
      put 'change_status'
    end
    
    collection do
      get 'my'
    end
  end
  
  resources :qresponses do
    collection do
      get 'my'
    end
  end
  
  resources :participation_messages do
    
  end
  
  
  resources :userprofiles
  resources :cboprofiles
  resources :cbos
  resources :categories
  resources :participations
  resources :communities
  resources :user_community_memberships
  resources :cbo_community_memberships
  
  resources :pages
  resources :subscriptions

    

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"
  

end

app/models/membership.rb
class Membership < ActiveRecord::Base
=begin
  attr_accessible :confirmed, :cbo_id, :user_id
  # 0 = not confirmed - admin needs to read
  # 1 = admin confirmed - CBO needs to read
  # 2 = cbo read - pending - on hold for now
  # 3 = cbo read - denied
  # 4 = cbo read - accepted
  
  
  belongs_to :user,  :class_name => "User"
  belongs_to :cbo,      :class_name => "Cbo"
  has_one :qresponse
  
  def confirm!(level=4)
    #self.toggle!(:confirmed)
    self.confirmed = level
    self.save
  end
  

  def confirmed?
    self.confirmed != 0
  end
=end
end



# == Schema Information
#
# Table name: memberships
#
#  id                 :integer         not null, primary key
#  user_id            :integer
#  cbo_id             :integer
#  created_at         :datetime
#  updated_at         :datetime
#  confirmed          :integer         default(0)
#  question1_text     :text
#  question1_response :text
#

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
=begin  
  def new

  end
  
  def create
    
    
    #first need to check if such a membership already exists (pending or not)
    @cbo = Cbo.find_by_id(params[:membership][:cbo_id])
    
    
    if(Membership.all(:conditions => "cbo_id = " + params[:membership][:cbo_id].to_s + " AND user_id = " + current_user.id.to_s).count == 0)
      current_user.join_cbo!(@cbo)
      redirect_to @cbo.cboprofile, :flash => { :success => "You have applied to this CBO." }
      
    else
      redirect_to @cbo.cboprofile, :flash => { :error => "There was an error in processing your request." }
      
    end
    
  end
  
  def destroy
    membership = Membership.find_by_id(params[:id])
    user = membership.user
    cbo = membership.cbo
    user.leave_cbo!(cbo)
    if signed_in_user?
      redirect_to cbo.cboprofile, :flash => { :success => "You have successfully left this CBO." }
      
    else
      redirect_to cbo, :flash => { :success => "You have successfully removed " + user.userprofile.name + "." }
      
    end
  end

  def confirm
    @title = "hello"
    membership = Membership.find_by_id(params[:id])
    confirm_level = params[:confirm_level].to_i
    membership.confirm!(params[:confirm_level].to_i)
    user = User.find_by_id(params[:membership][:user_id])
    cbo = Cbo.find_by_id(params[:membership][:cbo_id])
    redirect_to session[:return_to], :flash => { 
      :success => "#{user.userprofile.name} approved to level #{confirm_level} for #{cbo.cboprofile.name}" 
    }
  end

  def confirm0
    
  end
  
  def confirm1
    
  end
  
  def confirm2
    
  end
  
  def confirm3
    
  end
  
  def confirm4
    
  end
=end
  

end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_admin_confirm_form.html.erb
<!--

<%= form_for(membership, :as => :membership, :url => confirm_membership_path(membership), :method => :put) do |f| %>
	<%= f.hidden_field :cbo_id %>
	<%= f.hidden_field :user_id %>
	<%= select_tag :confirm_level, 
	
		"<option value=\"0\">0 - Admin Not Confirmed</option>
	      <option value=\"1\">1 - Admin Read - CBO Confirm</option>
	      <option value=\"2\">2 - CBO Read, Pending</option>
	      <option value=\"3\">3 - CBO Read, Denied</option>
	      <option value=\"4\">4 - CBO Read, Accepted</option>".html_safe %>
	
	<%= f.submit "Set Membership Level", :class => "btn primary"%>

	<% session[:return_to] = request.request_uri %>
	
<% end %>

!-->

app/views/memberships/_cbo_confirm_form.erb
<!--

<%= form_for(membership, :as => :membership, :url => confirm_membership_path(membership), :method => :put) do |f| %>
	<%= f.hidden_field :cbo_id %>
	<%= f.hidden_field :user_id %>
	<%= select_tag :confirm_level, 
	
		"<option value=\"1\">1 - Admin Read - CBO Confirm</option>
	      <option value=\"2\">2 - CBO Read, Pending</option>
	      <option value=\"3\">3 - CBO Read, Denied</option>
	      <option value=\"4\">4 - CBO Read, Accepted</option>".html_safe %>
	
	<%= f.submit "Set Membership Level", :class => "btn primary"%>
	
	<% session[:return_to] = request.request_uri %>

<% end %>

!-->

app/views/memberships/confirm.html.erb
<!--

Hello!

!-->