config/routes.rb
Tcproj::Application.routes.draw do
  
  
  get "subscriptions/create"

  get "subscriptions/destroy"

  get "qresponses/new"

  get "qresponses/show"

  get "qresponses/index"

  get "questionnaires/new"

  get "questionnaires/create"

  get "questionnaires/show"

  get "cbo_community_memberships/create"

  get "cbo_community_memberships/destroy"

  get "communities/new"

  get "communities/show"

  get "communities/index"

  get "user_community_memberships/create"

  get "user_community_memberships/destroy"

  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/nearby_cbos', :to => 'cboprofiles#nearby'
  match '/my_cbos', :to => 'cbos#my'
  match '/map', :to => 'pages#map'
  get "sessions/new"

  get "categorizations/new"
    
  
  root :to => "pages#home"
  
  resources :users do
    collection do
      get 'confirmpage'
      post 'confirm'
    end
  end
  
  resources :cbos do
    collection do
      get 'confirmpage'
      get 'my'
      post 'confirm'
    end
  end
  
  resources :cboprofiles do
    collection do
      get 'nearby'
    end
  end
  
  resources :communities do
    collection do
      get 'nearby'
      get 'my'
    end
  end
  
  resources :questionnaires do
    member do
      get 'reply'
    end
  end
  
  resources :pages do
    member do
      get 'map'
    end
  end
  
  resources :memberships do
    member do
      put 'confirm'
    end
  end
  
  resources :participations do
    member do
      put 'change_status'
    end
    
    collection do
      get 'my'
    end
  end
  
  resources :qresponses do
    collection do
      get 'my'
    end
  end
  
  resources :participation_messages do
    
  end
  
  
  resources :userprofiles
  resources :cboprofiles
  resources :cbos
  resources :categories
  resources :participations
  resources :communities
  resources :user_community_memberships
  resources :cbo_community_memberships
  
  resources :pages
  resources :subscriptions

    

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"
  

end

app/views/layouts/backup/_footer.html.erb
<footer>
        <p>&copy; The College Project 2011-2012</p>
</footer>

<%= debug(params) if Rails.env.development? %>

app/views/layouts/backup/_header.html.erb
<div class="topbar">
	<div class="fill">
		<div class="container">
			<h3><%= link_to "The College Project", root_path, :class => "brand" %></h3>
			
			<% if signed_in_user? %>


		
				<ul class="nav">
				
					<li><%= link_to "User Home", current_user %></li>
					<li><%= link_to current_user.userprofile.name.possessive + " Profile", current_user.userprofile %></li>
					<li><%= link_to "User Listing", users_path %></li>
					<li class="dropdown" data-dropdown="dropdown">
						<a href="#" class="dropdown-toggle">CBOs</a>
						<ul class="dropdown-menu">
						
							<% current_user.cbos.each do |cbo| %>
							<li><%= link_to cbo.cboprofile.name, cbo.cboprofile %></li>
							<% end %>
							<li><%= link_to "My CBOs", my_cbos_path %></li>
						
							<li class="divider"></li>
						
						
							<li><%= link_to "Nearby CBOS", nearby_cbos_path %></li>
							<li class="divider"></li>
							<li><%= link_to "All CBOS", cbos_path %></li>
							<li class="divider"></li>
							<li><%= link_to "View  Applications", my_qresponses_path %></li>
						</ul>
					</li>
					<li class="dropdown" data-dropdown="dropdown">
						<a href="#" class="dropdown-toggle">Communities</a>
						<ul class="dropdown-menu">
						
							<% current_user.communities.each do |community| %>
							<li><%= link_to community.name, community %></li>
							<% end %>
							<li><%= link_to "My Communities", my_communities_path %></li>
		
							<li class="divider"></li>
						
							<li><%= link_to "Nearby Communities", nearby_communities_path %></li>
						
							<li class="divider"></li>
						
							<li><%= link_to "All Communities", communities_path %></li>
						</ul>
					</li>
						
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>	
					<li><%= link_to "Sign Out", signout_path %></li>	
				
				</ul>	


			<% elsif signed_in_cbo? %>
				
				<ul class="nav">
				
					<li><%= link_to "CBO Home", current_cbo %></li>
					
					<li class="dropdown" data-dropdown="dropdown">
						<a href="#" class="dropdown-toggle">CBO Actions</a>
						<ul class="dropdown-menu">
							<li><%= link_to current_cbo.name.possessive + " Organization Profile", current_cbo.cboprofile %></li>
							<li class="divider"></li>
							<li><%= link_to "View Application Form", current_cbo.questionnaire %></li>
							<li><%= link_to "View  Applications", my_qresponses_path %></li>
						</ul>
					</li>
							
					
					
					<li><%= link_to "CBO Listing", cbos_path %></li>
					<li class="dropdown" data-dropdown="dropdown">
						<a href="#" class="dropdown-toggle">Communities</a>
						<ul class="dropdown-menu">
						
							<% current_cbo.communities.each do |community| %>
							<li><%= link_to community.name, community %></li>
							<% end %>
							<li><%= link_to "My Communities", my_communities_path %></li>

							<li class="divider"></li>
						
							<li><%= link_to "Nearby Communities", nearby_communities_path %></li>
							<li class="divider"></li>
							<li><%= link_to "All Communities", communities_path %></li>
						</ul>
					</li>						
				
				
					<li><%= link_to "Sign Out", signout_path %></li>
				
				</ul>
	
			<% else %>

				<ul class="nav">
					
					<li class="dropdown" data-dropdown="dropdown">
						<a href="#" class="dropdown-toggle">New</a>
						<ul class="dropdown-menu">
							<li><%= link_to "New User", signup_path %></li>
							<li><%= link_to "New CBO", new_cbo_path %></li>
						</ul>
					</li>
						
					<li><%= link_to "Sign In", signin_path %></li>
					
					<li><%= link_to "CBO Listing", cbos_path %></li>
				
				
				
				</ul>
				
				
				
			<% end %>
		</div>
	</div>
</div>

app/views/layouts/backup/_stylesheets.html.erb
<%= stylesheet_link_tag 'bootstrap', :media => 'screen' %>

app/views/layouts/backup/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag "jquery" %>
		
		<%= javascript_include_tag "bootstrap-dropdown" %>
		<%= javascript_include_tag "bootstrap-modal" %>
		<%= javascript_include_tag "tabs.js" %>
		
		<style type="text/css">
		      /* Override some defaults */
		      html, body {
		        background-color: #eee;
		      }
		      body {
		        padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
		      }
		      .container > footer p {
		        text-align: center; /* center align it with the container */
		      }
		      .container {
		        width: 940px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
		      }

		      /* The white background content wrapper */
		      .content {
		        background-color: #fff;
		        padding: 20px;
		        margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
		        -webkit-border-radius: 0 0 6px 6px;
		           -moz-border-radius: 0 0 6px 6px;
		                border-radius: 0 0 6px 6px;
		        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
		           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
		                box-shadow: 0 1px 2px rgba(0,0,0,.15);
		      }

		      /* Page header tweaks */
		      .page-header {
		        background-color: #f5f5f5;
		        padding: 20px 20px 10px;
		        margin: -20px -20px 20px;
		      }

		      /* Styles you shouldn't keep as they are for displaying this base example only 
		      .content .span10,
		      .content .span4 {
		        min-height: 500px;
		      }
		      /* Give a quick and non-cross-browser friendly divider 
		      .content .span4 {
		        margin-left: 0;
		        padding-left: 19px;
		        border-right: 1px solid #eee;
		      }
		*/

		      .topbar .btn {
		        border: 0;
		      }

		    </style>
	
	
	
	</head>
	<body>
		
		<%= render 'layouts/header' %>


		<div class="container">
			
			<div class="content">
				<%= render :partial => "shared/flash_messages", :locals => {:flash => flash} %>
		
	
				<%= yield %>
			</div>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>