config/routes.rb
Tcproj::Application.routes.draw do
  
  
  get "subscriptions/create"

  get "subscriptions/destroy"

  get "qresponses/new"

  get "qresponses/show"

  get "qresponses/index"

  get "questionnaires/new"

  get "questionnaires/create"

  get "questionnaires/show"

  get "cbo_community_memberships/create"

  get "cbo_community_memberships/destroy"

  get "communities/new"

  get "communities/show"

  get "communities/index"

  get "user_community_memberships/create"

  get "user_community_memberships/destroy"

  resources :sessions, :only => [:new, :create, :destroy]
  
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  match '/nearby_cbos', :to => 'cboprofiles#nearby'
  match '/my_cbos', :to => 'cbos#my'
  match '/map', :to => 'pages#map'
  get "sessions/new"

  get "categorizations/new"
    
  
  root :to => "pages#home"
  
  resources :users do
    collection do
      get 'confirmpage'
      post 'confirm'
    end
  end
  
  resources :cbos do
    collection do
      get 'confirmpage'
      get 'my'
      post 'confirm'
    end
  end
  
  resources :cboprofiles do
    collection do
      get 'nearby'
    end
  end
  
  resources :communities do
    collection do
      get 'nearby'
      get 'my'
    end
  end
  
  resources :questionnaires do
    member do
      get 'reply'
    end
  end
  
  resources :pages do
    member do
      get 'map'
    end
  end
  
  resources :memberships do
    member do
      put 'confirm'
    end
  end
  
  resources :participations do
    member do
      put 'change_status'
    end
    
    collection do
      get 'my'
    end
  end
  
  resources :qresponses do
    collection do
      get 'my'
    end
  end
  
  resources :participation_messages do
    
  end
  
  
  resources :userprofiles
  resources :cboprofiles
  resources :cbos
  resources :categories
  resources :participations
  resources :communities
  resources :user_community_memberships
  resources :cbo_community_memberships
  
  resources :pages
  resources :subscriptions

    

  get "pages/home"

  get "pages/contact"
  
  get "pages/about"
  

end

app/models/cbo.rb
class Cbo < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  attr_accessible :cboprofile_attributes
  attr_accessible :questionnaire_attributes
  
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,  :presence => true,
                    :length => { :maximum => 100 }
                    
  validates :email, :presence => true,
            :format => { :with => email_regex },
            :uniqueness => { :case_sensitive => false }
            
  validates :password,  :presence => true,
                        :confirmation => true,
                        :length => { :within => 6..16 }
                        
  before_save :encrypt_password
                    
  # has_many :opportunities
  
  #has_many :memberships #, :foreign_key => "cbo_id"
  #has_many :users, :through => :memberships, :source => :user
  
  has_many :subscriptions
  has_many :subscribed_users, :through => :subscriptions, :source => :user
  
  has_many :cbo_community_memberships
  has_many :communities, :through => :cbo_community_memberships, :source => :community
  
  has_many :participations
  has_many :participation_messages
  
  
  
  
  has_one :cboprofile
  #has_one :questionnaire
  
  accepts_nested_attributes_for :cboprofile
  #accepts_nested_attributes_for :questionnaire
                    
  def post_participation_message(participation, message)
    if self.participations.find_by_id(participation.id)
      # valid participation
      ParticipationMessage.create(:participation_id => participation.id,
                                  :user_or_cbo => 2,
                                  :user_id => participation.user_id,
                                  :cbo_id => self.id,
                                  :message => message)
                                  
    end
    
  end
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    cbo = find_by_email(email)
    return nil if cbo.nil?
    return cbo if cbo.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    cbo = find_by_id(id)
    (cbo && cbo.salt == cookie_salt) ? cbo : nil
  end
  
  def join_community!(community)
    self.cbo_community_memberships.create!(:community_id => community.id)
  end
  
  def leave_community!(community)
    self.cbo_community_memberships.find_by_community_id(community).destroy
  end
  
  def part_of_community?(community)
    return self.cbo_community_memberships.find_by_community_id(community)
  end
  
  
  
  
  def confirm!(level=1)
    self.toggle!(:confirmed)
  end
  
  def confirmed?
    self.confirmed != 0
  end
  
  
=begin  
  def confirmed_users_memberships(confirm_level = 4)
    self.memberships.find_all_by_confirmed(confirm_level)
  end
  
  def confirmed_users(confirm_level = 4)
    #self.cbos.find_all_by_confirmed
    
    #first, get the memberships
    #all_memberships = self.memberships.find_all_by_confirmed(confirm_level)
    users_list = Array.new
    self.confirmed_users_memberships(confirm_level).each do |membership|
      users_list.push(membership.user_id)
    end
    return User.find_all_by_id(users_list)
  end
  
  def pending_users_memberships
    self.confirmed_users_memberships(0)
  end
  
  def pending_users
    self.confirmed_users(0)
  end
  
  def approved_users_memberships
    self.confirmed_users_memberships([1,2])
  end
  
  def approved_users
    self.confirmed_users([1,2])
  end
  
  def rejected_users_memberships
    self.confirmed_users_memberships(3)
  end
  
  def rejected_users
    self.confirmed_users_memberships(3)
  end
  
  
  def confirm_user!(user)
    # check the user to make sure user is part of CBO's pending
    if user.pending_of_cbo?(self)
      self.memberships.find_by_user_id(user).confirm!
    end
  end
=end  
  
  
  private
  
    
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
    def encrypt_password
       self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
  
  
  
  
end



# == Schema Information
#
# Table name: cbos
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  confirmed          :integer         default(0)
#

app/controllers/cbos_controller.rb
class CbosController < ApplicationController
  rescue_from ActiveRecord::RecordNotUnique, :with => :record_not_unique 
  
  before_filter :authenticate_cbo, :only => [:edit, :update]
  before_filter :correct_cbo, :only => [:edit, :update]
  before_filter :check_confirmed_cbo, :only => [:show]
  before_filter :authenticate_user, :only => [:my]
  
  
  def new
    @title = "New CBO"
    @cbo = Cbo.new
    @cbo.build_cboprofile
    @cbo.build_questionnaire
  end
  
  def show
    @cbo = Cbo.find(params[:id])
    @subscribed_users = @cbo.subscribed_users.all
    
    @participations = @cbo.participations
    
=begin
    @approved_memberships = @cbo.all #@cbo.approved_users_memberships
    @confirmed_memberships = [] #@cbo.confirmed_users_memberships
    @rejected_memberships = [] #@cbo.rejected_users_memberships
=end

  end
  
  def edit
    @title = "Edit CBO"
  end
  
  def update
    if @cbo.update_attributes(params[:cbo])
      redirect_to @cbo, :flash => { :success => "CBO updated." }
    else
      @title = "Edit CBO"
      render 'edit'
    end
  end
  
  def my
    @cbos = current_user.subscribed_cbos
    @title = "My CBOs"
  end
  
  
  def confirmpage
    @title = "Confirm CBO"
    @cbo = Cbo.new
  end
  
  def confirm
    @title = "Confirm"
    
    #first, check their passwords
    cbo = Cbo.authenticate(params[:cbo][:email], params[:cbo][:password])
    if cbo.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Confirm CBO"
      @user = Cbo.new
      render 'confirmpage'
    else
      # ok, they're a real user. Confirm them.
      
      #have to re-add their password...
      cbo.password = params[:cbo][:password]
      
      if cbo.confirm!
        redirect_to signin_path, :notice => "CBO confirmed. Please sign in."
      end
    end
    
  end
  
  
  def index
    @cbos = Cbo.find_all_by_confirmed(1)
    @title = "All CBOs"
  end
  
  
  
  def create
    @cbo = Cbo.new(params[:cbo])
    if @cbo.save
      #sign_in_cbo @cbo
      #redirect_to @cbo
      redirect_to confirmpage_cbos_path, :notice => "CBO created. Please confirm your account here."
      
    else
      @title = "New CBO"
      @cbo.build_cboprofile(params[:cbo][:cboprofile_attributes])
      @cbo.build_questionnaire(params[:cbo][:questionnaire_attributes])
      render 'new'
    end
  end
  
  private
    def record_not_unique
      @cbo.errors.add(:email, "is already taken")
      render 'new'
    end
    
    def correct_cbo
      @cbo = Cbo.find(params[:id])
      redirect_to(root_path) unless current_cbo?(@cbo)
    end
    
    def check_confirmed_cbo
      # checks if the TARGET cbo is confirmed.
      @cbo = Cbo.find(params[:id])
      redirect_to(cbos_path) unless @cbo.confirmed?
    end

end

app/helpers/cbos_helper.rb
module CbosHelper
end

app/views/cbos/_admin_subscriptions.html.erb
<% if @cbo.subscribed_users.size > 0 %>
<p>Your organization currently has these followers:</p>


<%= render 'users_subscriptions_table', :subscribed_users => @subscribed_users %>


<%end %>

app/views/cbos/_cbos_grid_view.html.erb
<% cbos.each_slice(2) do |cbo_slice| %>
	<div class="row">
		<% cbo_slice.each do |cbo| %>
			<div class="span8">
				<%= render 'cboprofiles/mini_cell', :cboprofile => cbo.cboprofile %>
			</div>
		<% end %>
	</div>
	<br /><br />
<% end %>

app/views/cbos/_cbos_table.html.erb
<table>
	<thead>
		<tr>
			<th>Name</th>
		</tr>
	</thead>
	<tbody>
	<% cbos.each do |cbo| %>
		<tr>
			<td><%= link_to cbo.cboprofile.name, cbo.cboprofile %></td>
		</tr>
	<% end %>
	</tbody>
</table>

app/views/cbos/_fields.html.erb
<fieldset>
	<legend>Login Information</legend>
	<div class="clearfix">
		<%= cbo_form.label :name, :class => "xlInput" %>
		<div class="input">
			<%= cbo_form.text_field :name, :class => "xlarge" %>
		</div>
	</div>
	
	<div class="clearfix">
		<%= cbo_form.label :email, :class => "xlInput" %>
		<div class="input">
			<%= cbo_form.text_field :email, :class => "xlarge" %>
		</div>
	</div>
	
	<div class="clearfix">
		<%= cbo_form.label :password, :class => "xlInput" %>
		<div class="input">
			<%= cbo_form.password_field :password, :class => "xlarge" %>
		</div>
	</div>
	
	<div class="clearfix">
		<%= cbo_form.label :password_confirmation, "Password Again", :class => "xlInput" %>
		<div class="input">
			<%= cbo_form.password_field :password_confirmation, :class => "xlarge" %>
		</div>
	</div>
	
</fieldset>

app/views/cbos/_pending_users_table.html.erb
<!--

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Apply Date</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		<% cbo.pending_users_memberships.each do |membership| %>
		<tr>
			<td><%= link_to User.find_by_id(membership.user_id).userprofile.name, User.find_by_id(membership.user_id).userprofile %></td>
			<td><%= membership.updated_at.stamp("January 1, 1999 at 20:12")%></td>
			
			<td>
				<%= render 'memberships/cbo_confirm_form', :membership => membership, :cbo_id => current_cbo.id, :user_id => membership.user_id %>			
			</td>
			
		</tr>
		<% end %>
	</tbody>
</table>

!-->

app/views/cbos/_subscription.html.erb
<% if current_user.part_of_cbo?(@cbo) %>

	Unsubscribe from this CBO:<br /><br />
	<%= form_for(current_user.subscriptions.find_by_cbo_id(@cbo),
				:html => { :method => :delete }) do |f| %>
		<% f.submit "Unsubscribe", :class => "btn danger" %>
	<% end %>

<% else %>

	Subscribe to this CBO:<br /><br />
	<%= form_for(current_user.subscriptions.build(:cbo_id => @cbo.id)) do |f| %>
		<%= f.hidden_field :cbo_id %>
		<%= f.submit "Subscribe", :class => "btn primary"  %>
	<% end %>
<% end %>

app/views/cbos/_user_subscription.html.erb
<% if signed_in_user? %>
	<p>
	<% if current_user.subscribed?(cbo) %>
		<!-- Remove yourself from this CBO:<br /><br /> !-->
		<%= form_for(current_user.subscriptions.find_by_cbo_id(cbo),
					:html => { :method => :delete }) do |f| %>
			<% f.submit "Unsubscribe", :class => "btn danger" %>
		<% end %>


	<% else %>

		<!-- Be a part of this CBO:<br /><br /> !-->
		<%= form_for(current_user.subscriptions.build(:cbo_id => cbo.id)) do |f| %>
			<%= f.hidden_field :cbo_id %>
			<%= f.submit "Subscribe", :class => "btn primary"  %>
		<% end %>
	<% end %>
	</p>

<% end %>

app/views/cbos/_user_subscription_small.html.erb
<% if signed_in_user? %>


<p>
<% if current_user.subscribed?(cbo) %>
	<%= submit_tag "Subscribed", :class => "btn small disabled" %>
<% end%>

<p>
<% if current_user.subscribed?(cbo) %>
	<!-- Remove yourself from this CBO:<br /><br /> !-->
	<%= form_for(current_user.subscriptions.find_by_cbo_id(cbo),
				:html => { :method => :delete }) do |f| %>
		<% f.submit "Unsubscribe", :class => "btn small danger" %>
	<% end %>

<% else %>

	<!-- Be a part of this CBO:<br /><br /> !-->
	<%= form_for(current_user.subscriptions.build(:cbo_id => cbo.id)) do |f| %>
		<%= f.hidden_field :cbo_id %>
		<%= f.submit "Sunscribe", :class => "btn small primary"  %>
	<% end %>
<% end %>
</p>
<% end %>

app/views/cbos/_users_subscriptions_table.html.erb
<table>
	<thead>
		<tr>
			<th>Name</th>
		</tr>
	</thead>
	<tbody>
		<% subscribed_users.each do |user| %>
		<tr>
			<td><%= link_to user.userprofile.name, user.userprofile %></td>
			
		</tr>
		<% end %>
	</tbody>
</table>

app/views/cbos/confirmpage.html.erb
<h1>Confirm CBO</h1>

<%= form_for(@cbo, :url => { :action => "confirm" }) do |cbo_form| %>
	<%= render 'shared/error_messages', :object => cbo_form.object %>
	<p>Please re-enter your CBO e-mail and password to confirm your account.</p>
	
	<fieldset>
		<legend>Login Information</legend>
		<div class="clearfix">
			<%= cbo_form.label :email, :class => "xlInput" %>
			<div class="input">
				<%= cbo_form.text_field :email, :class => "xlarge" %>
			</div>
		</div>
		
		<div class="clearfix">
			<%= cbo_form.label :password, :class => "xlInput" %>
			<div class="input">
				<%= cbo_form.password_field :password, :class => "xlarge" %>
			</div>
		</div>
	
		<div class="actions">
			<%= cbo_form.submit "Confirm", :class => "btn primary"  %>
		</div>
	</fieldset>

<% end %>

app/views/cbos/edit.html.erb
<h1>Edit CBO</h1>

<%= form_for(@cbo) do |cbo_form| %>
	<%= render 'shared/error_messages', :object => cbo_form.object %>
	<%= render 'fields', :cbo_form => cbo_form %>
	
	<div class="actions">
		<%= cbo_form.submit "Update CBO" %>
	</div>
	
<% end %>

app/views/cbos/my.html.erb
<div class="page-header">
	<h1>My CBOs</h1>
</div>

<%= render 'cbos_grid_view', :cbos => @cbos %>






<% if current_user.subscribed_cbos.empty? %>
	<p>You are subscribed to any CBOs. See some nearby CBOs <%= link_to "here", nearby_cbos_path %>.</p>
<% end %>

app/views/cbos/new.html.erb
<h1>Create a new CBO</h1>

<%= form_for @cbo, :html => { :multipart => true } do |cbo_form| %>
	<%= render 'shared/error_messages', :object => cbo_form.object %>
	<%= render 'fields', :cbo_form => cbo_form %>
	
	<%= cbo_form.fields_for :cboprofile do |cboprofile_form| %>
		<%= render 'cboprofiles/fields', :cboprofile_form => cboprofile_form, :label => "Profile" %>	
	<% end %>
	
	
	
	<div class="actions">
		<%= cbo_form.submit "Create CBO", :class => "btn primary" %>
	</div>
	
<% end %>

app/views/cbos/show.html.erb
<h1><%= @cbo.name %></h1>
<p>
	<ul>
		<li>CBO Name: <%= @cbo.name %></li>
		<li>CBO Contact email: <%= @cbo.email %></li>
	</ul>
</p>

<% if signed_in_user? %>
	<%= render 'user_subscription', :cbo => @cbo %>

<% end %>

<% if current_cbo?(@cbo) %>
	<%= render 'admin_subscriptions', :cbo => @cbo %>
	<p><%= link_to "Edit Profile", edit_cbo_path(@cbo) %></p>
<% end %>

<% @participations.each do |participation| %>
	<%= link_to "Participation #{participation.id}", participation%>
<% end %>